/* (C)2026 */
package com.ricardomartinso.todolist.domain.task;

import com.ricardomartinso.todolist.domain.task.exceptions.TaskTransitionNotAllowedException;
import com.ricardomartinso.todolist.domain.task.vo.TaskId;
import com.ricardomartinso.todolist.domain.task.vo.TaskStatus;
import com.ricardomartinso.todolist.domain.task.vo.TaskTitle;
import com.ricardomartinso.todolist.domain.user.vo.UserId;
import java.time.LocalDateTime;

public class Task {
  private TaskId id;
  private TaskTitle title;
  private String description;
  private UserId ownerId;
  private TaskStatus status = TaskStatus.TODO;
  private boolean deleted = false;
  private LocalDateTime createdAt = LocalDateTime.now();
  private LocalDateTime updatedAt = LocalDateTime.now();

  private Task(TaskId id, TaskTitle title, String description, UserId ownerId) {
    this.id = id;
    this.title = title;
    this.description = description != null ? description.trim() : "";
    this.ownerId = ownerId;
  }

  /** Creates a new Task (ID will be generated by the database). */
  public static Task create(TaskTitle title, String description, UserId ownerId) {
    return new Task(null, title, description, ownerId);
  }

  public TaskId getId() {
    return id;
  }

  public TaskTitle getTitle() {
    return this.title;
  }

  public void rename(TaskTitle title) {
    this.title = title;
    this.update();
  }

  public void delete() {
    if (deleted) {
      return;
    }
    if (status == TaskStatus.DONE) {
      throw new TaskTransitionNotAllowedException("Cannot delete a done task");
    }
    this.deleted = true;
    this.update();
  }

  public void changeStatus(TaskStatus newStatus) {
    if (this.status == newStatus) {
      return;
    }
    if (this.deleted) {
      throw new TaskTransitionNotAllowedException("Cannot change status of a deleted task");
    }
    if (!status.canTransitionTo(newStatus)) {
      throw new TaskTransitionNotAllowedException(status, newStatus);
    }
    this.status = newStatus;
    this.update();
  }

  public String getDescription() {
    return this.description;
  }

  public void changeDescription(String description) {
    this.description = description.trim();
    this.update();
  }

  public boolean isDone() {
    return this.status == TaskStatus.DONE;
  }

  public boolean isDeleted() {
    return this.deleted;
  }

  public TaskStatus getStatus() {
    return this.status;
  }

  public boolean belongsToUser(UserId userId) {
    return this.ownerId.equals(userId);
  }

  public LocalDateTime getCreatedAt() {
    return createdAt;
  }

  public LocalDateTime getUpdatedAt() {
    return updatedAt;
  }

  public UserId getOwnerId() {
    return ownerId;
  }

  private void update() {
    this.updatedAt = LocalDateTime.now();
  }

  /**
   * Reconstitutes a Task from persistence layer data. This method should only be used by
   * infrastructure mappers.
   */
  public static Task reconstitute(
      TaskId id,
      TaskTitle title,
      String description,
      TaskStatus status,
      boolean deleted,
      UserId ownerId,
      LocalDateTime createdAt,
      LocalDateTime updatedAt) {
    Task task = new Task(id, title, description, ownerId);
    task.status = status;
    task.deleted = deleted;
    task.createdAt = createdAt;
    task.updatedAt = updatedAt;
    return task;
  }
}
